version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my-postgres-db
    environment:
      POSTGRES_PASSWORD: '123456' # Set password here
    ports:
      - '5432:5432'
    volumes:
      # Mount a local directory for persistent data
      - ./postgres-data:/var/lib/postgresql/data

      # Mount your SSL certs
      - ./certs:/etc/ssl/certs/postgres

# Define a top-level volume for data if you prefer that over a bind mount
# volumes:
#  postgres-data:
